# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
data-path="/opt/besu/data"
genesis-file="/opt/besu/genesis.json"
logging="INFO"
# node-private-key-file="/keys/nodekey"

# Transaction Pool
tx-pool="sequenced"
tx-pool-limit-by-account-percentage=1
# tx-pool-retention-hours=999
# tx-pool-max-size=1024

# P2P network
p2p-enabled=true
discovery-enabled=true
# static-nodes-file="/config/static/static-nodes.json"
p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25

host-allowlist=["*"]
min-gas-price=0
poa-block-txs-selection-max-time=100

# JSON-RPC
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH", "NET", "QBFT"]
rpc-http-cors-origins=["all"]
rpc-http-authentication-enabled=false
rpc-http-max-active-connections=80
revert-reason-enabled=true

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# Experimental / Extended Features
Xdns-enabled=true
Xdns-update-enabled=true
Xnat-kube-service-name="besu-node-validator-1"
engine-rpc-enabled=true



