version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:24.6.0
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --host-allowlist="*" --rpc-http-cors-origins="all"         --tx-pool=sequenced         --tx-pool-limit-by-account-percentage=1         --poa-block-txs-selection-max-time=100         --rpc-http-api=ADMIN,DEBUG,WEB3,ETH,TXPOOL,CLIQUE,MINER,NET; 
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./bootnode/data:/opt/besu/data
    ports:
      - 30303:30303
      - 8545:8545
    networks:
      besu-network:
        ipv4_address: 172.16.240.30
  node1:
    container_name: node1
    image: hyperledger/besu:24.6.0
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 2;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"         --poa-block-txs-selection-max-time=100         --tx-pool-limit-by-account-percentage=1         --tx-pool=sequenced 
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node1/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.31
  node2:
    container_name: node2
    image: hyperledger/besu:24.6.0
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 3;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"         --poa-block-txs-selection-max-time=100         --tx-pool-limit-by-account-percentage=1         --tx-pool=sequenced 
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node2/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.32
  node3:
    container_name: node3
    image: hyperledger/besu:24.6.0
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 4;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"         --poa-block-txs-selection-max-time=100         --tx-pool-limit-by-account-percentage=1         --tx-pool=sequenced 
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node3/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.33
