version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --host-allowlist="*" --rpc-http-cors-origins="all"         --rpc-http-api=ETH,NET,QBFT;
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./bootnode/data:/opt/besu/data
    ports:
      - 30303:30303
      - 8545:8545
    networks:
      besu-network:
        ipv4_address: 172.16.240.30
  node1:
    container_name: node1
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 20;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node1/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.31
  node2:
    container_name: node2
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 30;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node2/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.32
  node3:
    container_name: node3
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 40;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node3/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.33
  node4:
    container_name: node4
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 50;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node4/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.34
  node5:
    container_name: node5
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 60;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node5/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.35
  node6:
    container_name: node6
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 70;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --p2p-port=30303         --host-allowlist="*" --rpc-http-cors-origins="all"
    volumes:
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/genesis.json:/opt/besu/genesis.json
      - ./node6/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.36
