# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
data-path="/opt/besu/data"
genesis-file="/opt/besu/config/genesis.json"
logging="INFO"
# node-private-key-file="/keys/nodekey"
bootnodes=["enode://c3ef17460d9af36621514b0f1942a190781dd1d1df4a26d8106aaca7061b4d90303bd00c84896bd13e1a80440b54b61c54a75ae9f9393dcde01d4f8283359e4b@172.16.240.30:30303"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT"]
host-allowlist=["*"]
rpc-http-cors-origins=["all"]
p2p-host="0.0.0.0"
